// Generated by gencpp from file fishstatecontroller/State.msg
// DO NOT EDIT!


#ifndef FISHSTATECONTROLLER_MESSAGE_STATE_H
#define FISHSTATECONTROLLER_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fishstatecontroller
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : header()
    , state()
    , adjust()  {
    }
  State_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(_alloc)
    , adjust(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _adjust_type;
  _adjust_type adjust;





  typedef boost::shared_ptr< ::fishstatecontroller::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fishstatecontroller::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::fishstatecontroller::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::fishstatecontroller::State > StatePtr;
typedef boost::shared_ptr< ::fishstatecontroller::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fishstatecontroller::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fishstatecontroller::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fishstatecontroller::State_<ContainerAllocator1> & lhs, const ::fishstatecontroller::State_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.adjust == rhs.adjust;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fishstatecontroller::State_<ContainerAllocator1> & lhs, const ::fishstatecontroller::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fishstatecontroller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fishstatecontroller::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fishstatecontroller::State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fishstatecontroller::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fishstatecontroller::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fishstatecontroller::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fishstatecontroller::State_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fishstatecontroller::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3791bcc7f7d0d52403bf5e36635c950";
  }

  static const char* value(const ::fishstatecontroller::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3791bcc7f7d0d52ULL;
  static const uint64_t static_value2 = 0x403bf5e36635c950ULL;
};

template<class ContainerAllocator>
struct DataType< ::fishstatecontroller::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fishstatecontroller/State";
  }

  static const char* value(const ::fishstatecontroller::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fishstatecontroller::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"#time clock\n"
"string state\n"
"string adjust\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::fishstatecontroller::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fishstatecontroller::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.adjust);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fishstatecontroller::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fishstatecontroller::State_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
    s << indent << "adjust: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.adjust);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FISHSTATECONTROLLER_MESSAGE_STATE_H
