!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  ISO: 837
  awb_mode: tungsten
  brightness: 56
  contrast: 84
  exposure_compensation: 0
  exposure_mode: 'off'
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      ISO: 837
      awb_mode: tungsten
      brightness: 56
      contrast: 84
      exposure_compensation: 0
      exposure_mode: 'off'
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hFlip: false
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      saturation: 83
      sharpness: 0
      shutter_speed: 0
      state: true
      type: ''
      vFlip: false
      video_stabilisation: false
      zoom: 1.0
    state: []
  hFlip: false
  saturation: 83
  sharpness: 0
  shutter_speed: 0
  vFlip: false
  video_stabilisation: false
  zoom: 1.0
state: []
